### PR TITLE
Add bezier option

### PR DESCRIPTION
**Pull request by nehayward**
See #5

### CODE REVIEW

**Comment by gpbl** [comment]
Thanks @nehayward! Which issues are you referring to?

I don't get why [the diff](https://github.com/gpbl/SwiftChart/pull/36/files) is so big – would you mind to update only the lines that you have actually changed and describe what have you done?

**Comment by nehayward** [comment]
Ya I think it might have been the spacing that got changed. I'm not sure
what's causing it, but when the there are a certain amount of points the
bezier gets all messed up. I only added those two functions, the bezier
class and the bools to the chart series.

**Comment by gpbl** [comment]
I see you are using [this class](https://github.com/Ramshandilya/Bezier/blob/master/Bezier/CubicCurveAlgorithm.swift) by @ Ramshandilya (I wonder what are the best practices when including code from other people).

If you fix the diff I can join in and try to help 😊

**Comment by nehayward** [comment]
Ya I'm not sure maybe we should ask. I'll fix the diff.

**Comment by libern** [comment]
Is this still up for discussion?

**Pull request closed without merging**
