### PR TITLE
Xcode 10 and Swift 4.2 fix

### PR DESCRIPTION
**Pull request by yasinkavakli**
renamed *kCALineJoinBevel* to *CAShapeLayerLineJoin.bevel* so that SwiftChart is able to compile inside Xcode 10 and project set to Swift 4.2

This is my first PR on an open source project so if there is something false, please let me know 🙌

### CODE REVIEW

**Comment by dstranz** [comment]
@Coupz You could also add `s.swift_version = '4.2'` to SwiftChart.podspec file and update `.swift-version` file to `4.2`.

**Comment by Coupz** [comment]
Made the changes that @dstranz wrote above.

**Comment by dstranz** [comment]
Nice. Now we need to wait for @gpbl to accept this PR.

**Comment by Coupz** [comment]
@dstranz has updated the example project. Thanks for that 👍
Is this project alive @gpbl ?

**Comment by gpbl** [comment]
Yes it is alive again :) Sorry folks for the delays and thanks for the PR.

**Comment by pushchris** [comment]
@gpbl could we get a new release pushed out so that folks using pods can update? Thanks!

**Pull request merged**
